# Generated by Django 5.0.3 on 2024-03-23 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('department_status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
                ('user_image', models.FileField(default='user_default.jpg', upload_to='profile/')),
                ('user_status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='StdSem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StdSem_name', models.CharField(max_length=100)),
                ('StdSem_duration', models.CharField(max_length=100)),
                ('StdSem_status', models.IntegerField(default=1)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolAdmin.department')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_status', models.IntegerField(default=1)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolAdmin.department')),
                ('stdsem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolAdmin.stdsem')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_ids', models.CharField(max_length=50)),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_gender', models.CharField(max_length=50)),
                ('teacher_birthdate', models.DateField()),
                ('teacher_joindate', models.DateField()),
                ('teacher_qualification', models.CharField(max_length=100)),
                ('teacher_experience', models.CharField(max_length=100)),
                ('teacher_address', models.TextField()),
                ('teacher_mobile', models.CharField(max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolAdmin.users')),
            ],
        ),
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
                ('branch_address', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolAdmin.users')),
            ],
        ),
    ]
