# Generated by Django 5.0.3 on 2024-03-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_salary',
            field=models.IntegerField(default=0),
        ),
    ]
