# Generated by Django 5.0.3 on 2024-04-04 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolAdmin', '0002_teacher_teacher_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SchoolAdmin.users'),
        ),
    ]
