# Generated by Django 5.0.3 on 2024-03-12 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolAdmin', '0006_alter_branch_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('department_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='branch',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolAdmin.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_image',
            field=models.FileField(default='user_default.jpg', upload_to='profile/'),
        ),
    ]
