# Generated by Django 5.0.3 on 2024-03-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolAdmin', '0007_department_alter_branch_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_status',
            field=models.IntegerField(default=1),
        ),
    ]
