# Generated by Django 5.0.3 on 2024-03-12 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolAdmin', '0008_alter_department_department_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StdSem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StdSem_name', models.CharField(max_length=100)),
                ('StdSem_duration', models.CharField(max_length=100)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolAdmin.department')),
            ],
        ),
    ]
