# Generated by Django 5.0.3 on 2024-03-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolAdmin', '0009_stdsem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stdsem',
            name='StdSem_status',
            field=models.IntegerField(default=1),
        ),
    ]
