# Generated by Django 5.0.3 on 2024-03-13 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolAdmin', '0011_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='StdSem_id',
            new_name='stdsem_id',
        ),
    ]
