# Generated by Django 5.0.3 on 2024-03-20 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolAdmin', '0013_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_status',
        ),
    ]
